services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my-youtube-api
      POSTGRES_USER: admin-my-youtube
      POSTGRES_PASSWORD: "|6G&l}Ngn57K@9n3v~n'C6H!r"
  my-youtube:
    image: my-youtube-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__MyYoutubeApiDatabase: "Host=db;Username=admin-my-youtube;Password=|6G&l}Ngn57K@9n3v~n'C6H!r;Database=my-youtube-api"
      JwtSettings__Issuer: "MyYoutubeIssuer"
      JwtSettings__Audience: "MyYoutubeAudience"
      JwtSettings__SecretKey: "6zu[py'^VR5GG4%k/XIA+1SwP99'|SayOVOu:eJ)S1@zefamX4iLfIXTB/.ot8zZ6Y,m0,Ax64g`E69"
  poker-philippe:
    image: poker-philippe
    ports:
      - "8081:8081"
    restart: always
    environment:
      PORT: 8081
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - my-youtube
      - poker-philippe
    environment:
      #DOMAINS: "example.com -> http://app:8080, "
      DOMAINS: "my-youtube.jcl-web.freeboxos.fr -> http://my-youtube:8080, poker-philippe.jcl-web.freeboxos.fr -> http://poker-philippe:8081"
      #STAGE: "local" # Don't use production until staging works
      STAGE: "production" # Don't use production until staging works
      WEBSOCKET: true
      # FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data:
